# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b743fc5fc1621f167b724fc5743a8bc2879babd89d3d378be441e688a3ae4ed3833db2d1d7236a155648b04973ab9513b42ce2bcf7b6107417fc269f7f2a93c

test:
  secret_key_base: cba9ecd3512c1e69ab918b88a57a5ebaaaea6c35ad3347f43cba5c965733138c20b4ef9a33d59747eef26da8f95615ec418b5a12c2c433abd3bbdf4af7e5906c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
